version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@changesets/cli"
    versions:
    - 2.14.0
    - 2.15.0
    - 2.16.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: cssnano
    versions:
    - 4.1.11
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.13.0
    - 7.13.14
    - 7.13.8
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.13.13
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@11ty/eleventy"
    versions:
    - 0.12.1
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
