[build]
  command = "yarn build"
  publish = "build"

[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]
    checkPaths = ['/']

[[plugins]]
package = "netlify-plugin-subfont"

  [plugins.inputs]
    fallbacks = false

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-hashfiles"
