---
new_page_extension: md
auto_deploy: false
admin_path: content/admin
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: _site/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn eleventy
