---
new_page_extension: md
auto_deploy: false
admin_path: _site/admin
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*"
  exclude: "{package.json,netlify.toml}"
  templates:
  - base
- type: directory
  path: garden
  label: Garden
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - base
- type: document
  path: _data/reading.yml
  label: Reading
upload_dir: _site/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
