---
label: Base
hide_body: false
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: description
  type: text
  config:
    required: false
  label: Description
pages:
- garden/the-solution-to-overthinking.md
