---
label: Base
hide_body: false
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: description
  type: text
  config:
    required: false
  label: Description
pages:
- garden/investigating-the-passion-translation-of-the-bible.md
- garden/maintaining-a-brewfile-in-your-dotfiles.md
- garden/reflection-on-until-unity-by-francis-chan.md
- garden/the-importance-of-learning-a-version-control-system.md
- garden/the-solution-to-overthinking.md
- now.md
